[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 7

[general]
# get themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"]

[terminal]
[terminal.shell]
args = ["new-session", "-A", "-s", "term"]
program = "/opt/homebrew/bin/tmux"
